repos:
  - repo: git@github.com:Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package-lock.json

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1 # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        # non-recommended entry by pre-commit maintener, https://stackoverflow.com/a/64309843/1146018
        # ideally, a separate commit for code formatting, but much simpler 
        # to trigger formatting and re-staging as part of commit
        entry: bash -c 'npx prettier --write .; git add -u' --
