---
version: "3"

services:


  pp-server:
    container_name: pp-server
    environment:
      - NODE_OPTIONS="--max-old-space-size=2048"
    build:
      context: ./
      dockerfile: ./build/full/Dockerfile
      args: 
        platform: "aarch64"
    ports:
      - 3456:3000


    volumes:
      - ./:/home/node/app/
      - /Users/azaldiva/data/tp:/home/root/pp/tp/
      - /Users/azaldiva/proteinpaint/bare:/home/root/pp/active/
      - exclude:/home/node/app/node_modules

  pp-client:
    container_name: pp-client
    environment:
      - NODE_OPTIONS="--max-old-space-size=2048"

    build:
      context: ./
      dockerfile: ./client/Dockerfile
    command: bash -c "rm -rf /home/node/app/node_modules/* && PP_MODE=container-prod npx proteinpaint"
    volumes:
      - ./client:/home/node/app/
      - exclude:/home/node/app/node_modules
      - /Users/azaldiva/data/tp:/home/root/pp/tp/
      - /Users/azaldiva/proteinpaint/bare:/home/root/pp/active/
    ports:
      - 80:3000

volumes:
  exclude: null