name: "Create Release"

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release type
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

      include:
        type: choice
        description: Include
        options:
          - npm packages + Docker image
          - npm packages only

      build_secret:
        type: string
        description: Build secret

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 20
    outputs:
      updated_rust: ${{ steps.version_bump.outputs.updated_rust }}
    steps:
      - name: Check secret
        run: |
          if [ "${{ github.event.inputs.build_secret }}" != "${{ secrets.BUILD_SECRET }}" ]; then
            echo "Wrong build secret."
            exit 1
          fi

      - name: Check user permission
        id: check
        uses: scherermichael-oss/action-has-permission@master
        with:
          required-permission: write
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Exit if user doesn't have write permission
        run: |
          if [ "${{ steps.check.outputs.has-permission }}" = "false" ]
            then
            echo "Only users with write permission are allowed to execute this workflow manually."
            exit 1
          fi

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch All Tags
        run: git fetch --all --tags

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sjcrh'
      - run: npm ci

      - name: Run version bump
        id: version_bump
        run: |
          exclude="";

          if [ "${{ github.event.inputs.include }}" = "npm packages only" ]; then
            exclude="-x=container";
          fi

          . ./build/ci-version-update.sh ${{ github.event.inputs.release_type }} -w $exclude
          
          echo "::set-output name=tag_name::$TAG"
          
          ./build/ci-npm-publish.sh "$UPDATED"
          
          echo "::set-output name=updated_workspaces::$UPDATED"   
          
          if [[ $UPDATED == *"rust"* ]]; then
             echo "::set-output name=updated_rust::true"
          else
            echo "::set-output name=updated_rust::false"
          fi
          
          CHANGES=$(node build/getLatestReleaseChanges.js)
          echo "::set-output name=latest_release_changes::$CHANGES"

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version_bump.outputs.tag_name }}
          release_name: ${{ steps.version_bump.outputs.tag_name }}
          body: |
            ${{ steps.version_bump.outputs.latest_release_changes }}
          draft: false
          prerelease: false

  rust-build:
    if: needs.publish-npm.outputs.updated_rust == 'true'
    needs: publish-npm
    uses: ./.github/workflows/CI-rust-build.yml

  upload-rust-assets:
    needs: rust-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Download Rust Binaries
        uses: actions/download-artifact@v4
        with:
          name: rust-binaries
          path: rust-binaries

      - name: Rename Rust Binaries
        id: rename_rust_binaries
        run: |
          PP_RUST_TAG="$(node -p "require('./rust/package.json').version")";
          PP_TAG="$(node -p "require('./package.json').version")";
          echo "::set-output name=pp_tag::PP_TAG";
          RENAMED="rust-binaries-$PP_RUST_TAG-linux-x64.tar.gz"
          tar -czvf "$RENAMED" -C rust-binaries .
          echo "::set-output name=renamed_rust_binaries::$RENAMED";

      - uses: AButler/upload-release-assets@v3.0
        with:
          files: "${{ steps.rename_rust_binaries.outputs.renamed_rust_binaries }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.rename_rust_binaries.outputs.pp_tag }}


  publish-docker-no-new-rust-module:
    if: needs.publish-npm.outputs.updated_rust == 'false' && github.event.inputs.include == 'npm packages + Docker image'
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - name: Publish docker image
        uses: stjude/proteinpaint/.github/actions/publish-docker@rust_ci_build
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_ACTOR: ${{ github.actor }}

  publish-docker-with-new-rust-module:
    if: github.event.inputs.include == 'npm packages + Docker image'
    needs: upload-rust-assets
    runs-on: ubuntu-latest
    steps:
      - name: Publish docker image
        uses: stjude/proteinpaint/.github/actions/publish-docker@rust_ci_build
        with:
          PAT: ${{ secrets.PAT }}
          GITHUB_ACTOR: ${{ github.actor }}