name: Publish Blat Server Image

on:
  workflow_dispatch:
    inputs:
      build_secret:
        type: string
        description: Build secret

  push:
    branches:
      - add-blat-server-image

jobs:
  check-user-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check user permission
        uses: stjude/proteinpaint/.github/actions/check-user-permissions@master
        with:
          BUILD_SECRET: ${{ secrets.BUILD_SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_BUILD_SECRET: ${{ github.event.inputs.build_secret }}

  build:
    needs: check-user-permissions
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Login to GitHub Container Registry
        run: |
          echo $CR_PAT | docker login ghcr.io -u stjude --password-stdin
        env:
          CR_PAT: ${{ secrets.PAT }}


      - name: Build image
        run: |
          cd container/blat
          sh build.sh
          
          docker push ghcr.io/stjude/blat:latest
